{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject.get('project').get('name') %}
{% set description = pyproject.get('project').get('description') %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}
{% set license = pyproject.get('project').get('license') %}
{% set home = pyproject.get('project', {}).get('urls', {}).get('Homepage', '') %}
{% set build_deps = pyproject.get("build-system", {}).get("requires", []) %}
{% set deps = pyproject.get('project', {}).get('dependencies', []) %}
{% set conda_deps = pyproject.get('tool', {}).get('conda', {}).get('environment', {}).get('dependencies',[]) %}
{% set test_deps = pyproject.get('project', {}).get('optional-dependencies', {}).get('test',[]) %}

package:
  name: alinea.adel
  version: "2.0.2"

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  string: py{{ PY_VER }}
  script: {{PYTHON}} -m pip install .

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
    - openalea.deploy
  run:
    - python >=3.6
    - openalea.mtg
    - scipy
    - rpy2
    - alinea.caribu
    - openalea.astk

test:
  requires:
    - pytest
  imports:
    - alinea.adel
  source_files:
    - test/**
    - test/data/**
  commands:
    - cd test
    - pytest -v --ignore=test_povray.py --ignore=test_dataflow.py --ignore=test_plantgen.py

about:
  home: {{ home }}
  license: Cecill-C License
  license_file: LICENCE.txt
  summary: {{ description }}

